server:
  port: 9100

eventstore:
  endpoint: esdb://localhost:2113?tls=false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/rankme
