server:
  port: 9100
spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:9900
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        default:
          consumer:
            anonymousGroupPrefix: ${spring.application.name}-${server.port}.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka
gateway:
  url: http://localhost:9700
application:
  id:
  key: