server:
  port: 9040
spring:
  application:
    name: api-service
  config:
    import: optional:configserver:http://localhost:9010
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        commands-out-0:
          destination: RankMe
      rabbit:
        bindings:
          commands-out-0:
            producer:
              routingKeyExpression: headers['type']
        default:
          consumer:
            anonymousGroupPrefix: ${spring.application.name}-${server.port}.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9030/eureka
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
graphiql:
  mapping: /graphiql
  enabled: true
  cdn:
    enabled: false
    version: 0.13.0
gateway:
  url: http://localhost:9020