server:
  port: 9100

eventstore:
  endpoint: esdb://localhost:2113?tls=false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
