server:
  port: 9100

spring:
  application:
    name: command-service
  config:
    import: optional:configserver:http://dev:9900/
  profiles:
    active: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/rankme
    username: postgres
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
