server:
  port: 9100

eventstore:
  endpoint: esdb://localhost:2113?tls=false

spring:
  profiles:
    active: eventstore
  datasource:
    url: jdbc:postgresql://localhost:5432/rankme
    username: postgres
    password: devpass
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
