version: '3.4'

services:
  postgres:
    image: library/postgres:13.1-alpine
    environment:
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=rankme
    ports:
      - 5432:5432

  rabbitmq:
    image: library/rabbitmq:3.8.9-management
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: library/mongo:4.4.2
    ports:
      - 27017:27017
