version: '3.4'

services:
  postgres:
    image: library/postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: rankme
    ports:
      - "5432:5432"

  rabbitmq:
    image: library/rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: library/mongo:4.4.2
    ports:
      - "27017:27017"

  config-service:
    build: config-service
    ports:
      - "9010:9010"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS: classpath:config/docker
      SPRING_RABBITMQ_HOST: rabbitmq
      WAIT_RABBITMQ: rabbitmq:15672

  gateway-service:
    build: gateway-service
    ports:
      - "9020:9020"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9010/
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_CONFIG_SERVICE: config-service:9010
      WAIT_DISCOVERY_SERVICE: discovery-service:9030

  discovery-service:
    build: discovery-service
    ports:
      - "9030:9030"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9010/
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_CONFIG_SERVICE: config-service:9010

  api-service:
    build: api-service
    ports:
      - "9040:9040"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9010/
      WAIT_CONFIG_SERVICE: config-service:9010
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_DISCOVERY_SERVICE: discovery-service:9030

  command-service:
    build: command-service
    ports:
      - "9050:9050"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9010/
      WAIT_CONFIG_SERVICE: config-service:9010
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_POSTGRES: postgres:5432

  query-service:
    build: query-service
    ports:
      - "9060:9060"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9010/
      WAIT_CONFIG_SERVICE: config-service:9010
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_MONGODB: mongodb:27017
      WAIT_DISCOVERY_SERVICE: discovery-service:9030

  subscription-service:
    build: api-service
    ports:
      - "9070:9070"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9010/
      WAIT_CONFIG_SERVICE: config-service:9010
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_DISCOVERY_SERVICE: discovery-service:9030
