version: '3.4'

services:
  postgres:
    image: library/postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: rankme
    ports:
      - "5432:5432"

  rabbitmq:
    image: library/rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: library/mongo:4.4.2
    ports:
      - "27017:27017"

  config-service:
    build: config-service
    ports:
      - "9900:9900"
    environment:
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS: classpath:config/docker
      SPRING_RABBITMQ_HOST: rabbitmq
      WAIT_RABBITMQ: rabbitmq:15672

  discovery-service:
    build: discovery-service
    ports:
      - "9800:9800"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9900/
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_CONFIG_SERVICE: config-service:9900

  gateway-service:
    build: gateway-service
    ports:
      - "9700:9700"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9900/
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_CONFIG_SERVICE: config-service:9900
      WAIT_DISCOVERY_SERVICE: discovery-service:9800

  api-service:
    build: api-service
    ports:
      - "9000:9000"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9900/
      WAIT_CONFIG_SERVICE: config-service:9900
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_DISCOVERY_SERVICE: discovery-service:9800

  command-service:
    build: command-service
    ports:
      - "9200:9200"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9900/
      WAIT_CONFIG_SERVICE: config-service:9900
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_POSTGRES: postgres:5432

  query-service:
    build: query-service
    ports:
      - "9300:9300"
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-service:9900/
      WAIT_CONFIG_SERVICE: config-service:9900
      WAIT_RABBITMQ: rabbitmq:15672
      WAIT_MONGODB: mongodb:27017
      WAIT_DISCOVERY_SERVICE: discovery-service:9800

