graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  cdn:
    enabled: false
    version: 0.13.0
spring:
  profiles:
    active: dev
