server:
  port: 9020
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:9010
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
      routes:
        - id: query-service
          uri: lb://QUERY-SERVICE
          predicates:
            - Path=/query-service/**
          filters:
            - RewritePath=/query-service/(?<segment>.*), /$\{segment}
        - id: api-service
          uri: lb://API-SERVICE
          predicates:
            - Path=/api
            - Method=GET,POST,OPTIONS
          filters:
            - RewritePath=/api, /graphql
        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/subscriptions/**
    stream:
      rabbit:
        default:
          consumer:
            anonymousGroupPrefix: ${spring.application.name}-${server.port}.
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9030/eureka
