server:
  port: 9700
spring:
  application:
    name: gateway-service
  config:
    import: ${CONFIG_SERVICE_URI:optional:configserver:http://localhost:9900}
  cloud:
    gateway:
      routes:
        - id: query-service
          uri: lb://QUERY-SERVICE
          predicates:
          - Path=/query-service/**
          filters:
          - RewritePath=/query-service/(?<segment>.*), /$\{segment}
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9800/eureka
