graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  enabled: true
  cdn:
    enabled: false
    version: 0.13.0

eventstore:
  host: localhost
  port: 2113