server:
  port: 9070
spring:
  application:
    name: subscription-service
  config:
    import: optional:configserver:http://localhost:9010
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: playerCreatedConsumer
    stream:
      bindings:
        playerCreatedConsumer-in-0:
          destination: RankMe
      rabbit:
        bindings:
          playerCreatedConsumer-in-0:
            consumer:
              bindingRoutingKey: query-player-created
              anonymousGroupPrefix: player-created-subscriber-
        default:
          consumer:
            anonymousGroupPrefix: ${spring.application.name}-${server.port}.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9030/eureka
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
graphiql:
  mapping: /graphiql
  enabled: true
  cdn:
    enabled: false
    version: 0.13.0