spring:
  rabbitmq:
    host: dev
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://dev:27017/rankme
eureka:
  client:
    service-url:
      defaultZone: http://dev:9800/eureka
