server:
  port: 9800
spring:
  application:
    name: discovery-service
  config:
    import: ${CONFIG_SERVICE_URI:optional:configserver:http://localhost:9900}
eureka:
  server:
    maxThreadsForPeerReplication: 0
  client:
    register-with-eureka: false
    fetch-registry: false
