server:
  port: 9800
spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:http://localhost:9900
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      rabbit:
        default:
          consumer:
            anonymousGroupPrefix: ${spring.application.name}-${server.port}.
eureka:
  server:
    maxThreadsForPeerReplication: 0
  client:
    register-with-eureka: false
    fetch-registry: false
