server:
  port: 9060
spring:
  application:
    name: query-service
  config:
    import: optional:configserver:http://localhost:9010
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: "leagueCreatedConsumer;leagueRenamedConsumer;leagueSettingsChangedConsumer;\
        playerCreatedConsumer;playerPlayedGameConsumer;\
        gameScheduledConsumer;gamePlayedConsumer"
    stream:
      bindings:
        leagueCreatedConsumer-in-0:
          destination: RankMe
          group: league-created-consumer-group
        leagueRenamedConsumer-in-0:
          destination: RankMe
          group: league-renamed-consumer-group
        leagueSettingsChangedConsumer-in-0:
          destination: RankMe
          group: league-settings-changed-consumer-group
        playerCreatedConsumer-in-0:
          destination: RankMe
          group: player-created-consumer-group
        playerPlayedGameConsumer-in-0:
          destination: RankMe
          group: player-played-game-consumer-group
        gameScheduledConsumer-in-0:
          destination: RankMe
          group: game-scheduled-consumer-group
        gamePlayedConsumer-in-0:
          destination: RankMe
          group: game-played-consumer-group
        notifications-out-0:
          destination: RankMe
      rabbit:
        bindings:
          leagueCreatedConsumer-in-0.consumer.bindingRoutingKey: league-created
          leagueRenamedConsumer-in-0.consumer.bindingRoutingKey: league-renamed
          leagueSettingsChangedConsumer-in-0.consumer.bindingRoutingKey: league-settings-changed
          playerCreatedConsumer-in-0.consumer.bindingRoutingKey: player-created
          playerPlayedGameConsumer-in-0.consumer.bindingRoutingKey: player-played-game
          gameScheduledConsumer-in-0.consumer.bindingRoutingKey: game-scheduled
          gamePlayedConsumer-in-0.consumer.bindingRoutingKey: game-played
          notifications-out-0.producer.routingKeyExpression: headers['type']
        default:
          consumer:
            anonymousGroupPrefix: ${spring.application.name}-${server.port}.
  data:
    mongodb:
      uri: mongodb://localhost:27017/rankme
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9030/eureka
