server:
  port: 9200

spring:
  application:
    name: query-service
  config:
    import: optional:configserver:http://dev:9900/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://localhost:27017/rankme
