spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
gateway:
  url: http://gateway-service:9700
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:9800/eureka
