spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
eureka:
  server:
    maxThreadsForPeerReplication: 0
  client:
    register-with-eureka: false
    fetch-registry: false